services:
    coreshop.registry.tracking.tracker:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - CoreShop\Component\Tracking\Tracker\TrackerInterface
            - 'tracker'

    coreshop.registry.tracking.extractor:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - CoreShop\Component\Tracking\Extractor\TrackingExtractorInterface
            - 'tracking-extractor'

    coreshop.tracking.resolver.tracking_config: '@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface'
    CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface: '@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolver'
    CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolver:
        public: true
        arguments:
            - '@Pimcore\Analytics\SiteId\SiteIdProvider'
            - '@Pimcore\Analytics\Google\Config\ConfigProvider'

    coreshop.tracking.tracker.ecommerce_tracker: '@CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker'
    CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker:
        abstract: true
        arguments:
            - '@templating.engine.delegating'

    coreshop.tracking.event.gtm_code_tracker: '@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker'
    CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker:
        public: true

    CoreShop\Bundle\TrackingBundle\EventListener\GtmDataLayerBlockListener:
        public: true
        arguments:
            - '@Pimcore\Http\Request\Resolver\PimcoreContextResolver'
            - '@Pimcore\Http\ResponseHelper'
            - '@Pimcore\Analytics\SiteId\SiteIdProvider'
            - '@event_dispatcher'
            - '@templating.engine.delegating'
            - '@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100 }

    coreshop.tracking.tracker.google.analytics.enhanced_ecommerce: '@CoreShop\Bundle\TrackingBundle\Tracker\Google\AnalyticsEnhancedEcommerce'
    CoreShop\Bundle\TrackingBundle\Tracker\Google\AnalyticsEnhancedEcommerce:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Google\Tracker']]
            - [setConfigResolver, ['@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-analytics-enhanced-ecommerce }

    coreshop.tracking.tracker.google.analytics.universal_ecommerce: '@CoreShop\Bundle\TrackingBundle\Tracker\Google\UniversalEcommerce'
    CoreShop\Bundle\TrackingBundle\Tracker\Google\UniversalEcommerce:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Google\Tracker']]
            - [setConfigResolver, ['@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-analytics-universal-ecommerce }

    coreshop.tracking.tracker.google.analytics.gtag_enhanced_ecommerce: '@CoreShop\Bundle\TrackingBundle\Tracker\Google\GlobalSiteTagEnhancedEcommerce'
    CoreShop\Bundle\TrackingBundle\Tracker\Google\GlobalSiteTagEnhancedEcommerce:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Google\Tracker']]
            - [setConfigResolver, ['@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-gtag-enhanced-ecommerce }

    coreshop.tracking.tracker.google.analytics.gtm_classic_ecommerce: '@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\TagManagerClassicEcommerce'
    CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\TagManagerClassicEcommerce:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        public: true
        calls:
            - [setCodeTracker, ['@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker']]
            - [setConfigResolver, ['@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-gtm-classic-ecommerce }

    coreshop.tracking.tracker.google.analytics.gtm_enhanced_ecommerce: '@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\TagManagerEnhancedEcommerce'
    CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\TagManagerEnhancedEcommerce:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        public: true
        calls:
            - [setCodeTracker, ['@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker']]
            - [setConfigResolver, ['@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolverInterface']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-gtm-enhanced-ecommerce }

    coreshop.tracking.tracker.matomo: '@CoreShop\Bundle\TrackingBundle\Tracker\Matomo\Matomo'
    CoreShop\Bundle\TrackingBundle\Tracker\Matomo\Matomo:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Piwik\Tracker']]
        tags:
            - { name: coreshop.tracking.tracker, type: matomo }

    coreshop.tracking.extractor: '@CoreShop\Component\Tracking\Extractor\TrackingExtractorInterface'
    CoreShop\Component\Tracking\Extractor\TrackingExtractorInterface: '@CoreShop\Component\Tracking\Extractor\CompositeExtractor'
    CoreShop\Component\Tracking\Extractor\CompositeExtractor:
        arguments:
            - '@coreshop.registry.tracking.extractor'

    coreshop.tracking.manager:
        alias: 'CoreShop\Component\Tracking\Tracker\TrackerInterface'
        public: true

    CoreShop\Component\Tracking\Tracker\TrackerInterface:
        alias: 'CoreShop\Component\Tracking\Tracker\CompositeTracker'
        public: true

    CoreShop\Component\Tracking\Tracker\CompositeTracker:
        public: true
        arguments:
            - '@CoreShop\Component\Tracking\Extractor\TrackingExtractorInterface'
            - '@coreshop.registry.tracking.tracker'
