services:
    coreshop.registry.tracking.tracker:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - CoreShop\Bundle\TrackingBundle\Tracker\EcommerceTrackerInterface
            - 'tracker'

    coreshop.tracking.item_builder:
        class: CoreShop\Bundle\TrackingBundle\Builder\ItemBuilder
        public: true
        arguments:
            - '@coreshop.order.purchasable.price_calculator'

    coreshop.tracking.resolver.tracking_config:
        class: CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolver
        public: true
        arguments:
            - '@Pimcore\Analytics\SiteId\SiteIdProvider'
            - '@Pimcore\Analytics\Google\Config\ConfigProvider'

    coreshop.tracking.tracker.ecommerce_tracker:
        class: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        abstract: true
        arguments:
            - '@templating.engine.delegating'
            - '@coreshop.tracking.item_builder'
            - '@coreshop.context.currency'

    coreshop.tracking.event.gtm_code_tracker:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker
        public: true

    coreshop.tracking.event.gtm_code_event:
        class: CoreShop\Bundle\TrackingBundle\EventListener\GtmDataLayerBlockListener
        public: true
        arguments:
            - '@Pimcore\Http\Request\Resolver\PimcoreContextResolver'
            - '@Pimcore\Http\ResponseHelper'
            - '@Pimcore\Analytics\SiteId\SiteIdProvider'
            - '@event_dispatcher'
            - '@templating.engine.delegating'
            - '@coreshop.tracking.event.gtm_code_tracker'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100 }

    coreshop.tracking.tracker.google.analytics.enhanced_ecommerce:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Google\AnalyticsEnhancedEcommerce
        parent: coreshop.tracking.tracker.ecommerce_tracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Google\Tracker']]
            - [setConfigResolver, ['@coreshop.tracking.resolver.tracking_config']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-analytics-enhanced-ecommerce }

    coreshop.tracking.tracker.google.analytics.universal_ecommerce:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Google\UniversalEcommerce
        parent: coreshop.tracking.tracker.ecommerce_tracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Google\Tracker']]
            - [setConfigResolver, ['@coreshop.tracking.resolver.tracking_config']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-analytics-universal-ecommerce }

    coreshop.tracking.tracker.google.analytics.gtag_enhanced_ecommerce:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Google\GlobalSiteTagEnhancedEcommerce
        parent: coreshop.tracking.tracker.ecommerce_tracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Google\Tracker']]
            - [setConfigResolver, ['@coreshop.tracking.resolver.tracking_config']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-gtag-enhanced-ecommerce }

    coreshop.tracking.tracker.google.analytics.gtm_classic_ecommerce:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\TagManagerClassicEcommerce
        parent: coreshop.tracking.tracker.ecommerce_tracker
        public: true
        calls:
            - [setCodeTracker, ['@coreshop.tracking.event.gtm_code_tracker']]
            - [setConfigResolver, ['@coreshop.tracking.resolver.tracking_config']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-gtm-classic-ecommerce }

    coreshop.tracking.tracker.google.analytics.gtm_enhanced_ecommerce:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\TagManagerEnhancedEcommerce
        parent: coreshop.tracking.tracker.ecommerce_tracker
        public: true
        calls:
            - [setCodeTracker, ['@coreshop.tracking.event.gtm_code_tracker']]
            - [setConfigResolver, ['@coreshop.tracking.resolver.tracking_config']]
        tags:
            - { name: coreshop.tracking.tracker, type: google-gtm-enhanced-ecommerce }

    coreshop.tracking.tracker.matomo:
        class: CoreShop\Bundle\TrackingBundle\Tracker\Matomo\Matomo
        parent: coreshop.tracking.tracker.ecommerce_tracker
        public: true
        calls:
            - [setTracker, ['@Pimcore\Analytics\Piwik\Tracker']]
        tags:
            - { name: coreshop.tracking.tracker, type: matomo }

    coreshop.tracking.manager:
        class: CoreShop\Bundle\TrackingBundle\Manager\TrackingManager
        public: true
        arguments:
            - '@coreshop.registry.tracking.tracker'