core_shop_tracking:
    trackers:
        google-analytics-enhanced-ecommerce:
            enabled: false
        google-analytics-universal-ecommerce:
            enabled: false
        google-tag-enhanced-ecommerce:
            enabled: false
        piwik:
            enabled: false